TaskManagerMVC/TaskManager/Controllers/CommentsController.cs
namespace TaskManager.Controllers
{
    using DataAccess.Entities;
    using DataAccess.Repositories;
    using System.Web.Mvc;
    using Models;
    using VIewModels.TaskManager;
    using System;

    public class CommentsController : BaseController<Comment, ByIdCommentVM, AllCommentsVM, CommentsFilter>
    {
        protected override AllCommentsVM CreateBaseAllVM()
        {
            return new AllCommentsVM();
        }

        protected override ByIdCommentVM CreateBaseByIdVM()
        {
            return new ByIdCommentVM();
        }

        protected override BaseRepo<Comment> CreateRepository()
        {
            return RepositoryFactory.GetCommentsRepository();
        }

        protected override void PopulateViewModel(ByIdCommentVM model, Comment entity)
        {
            int taskId = Convert.ToInt32(this.Request["taskID"]);
            if (entity.Id <= 0)
            {
                model.Id = entity.Id;
                model.TaskId = taskId;
                model.CreatedBy = AuthenticationManager.LoggedUser.Id;
                model.Comments = entity.Comments;
            }
            else
            {
                model.Id = entity.Id;
                model.TaskId = entity.TaskId;
                model.CreatedBy = AuthenticationManager.LoggedUser.Id;
                model.Comments = entity.Comments;
            }
        }

        protected override void PopulateEntity(Comment entity, ByIdCommentVM model)
        {
            entity.Id = model.Id;
            entity.TaskId = model.TaskId;
            entity.CreatedBy = model.CreatedBy;
            entity.Comments = model.Comments;
        }

        protected override ActionResult Redirect(Comment entity)
        {
           return RedirectToAction("Details","TasksManager", new { id=entity.TaskId }); 
        }
    }
}

TaskManagerMVC/TaskManager/Controllers/LoggedWorkController.cs
namespace TaskManager.Controllers
{
    using DataAccess.Entities;
    using DataAccess.Repositories;
    using System;
    using System.Web.Mvc;
    using Models;
    using VIewModels.TaskManager;

    public class LoggedWorkController : BaseController<LoggedWork, ByIdLoggedWorkVM, AllLoggedWorkVM, LoggedWorksFilter>
    {
        protected override AllLoggedWorkVM CreateBaseAllVM()
        {
            return new AllLoggedWorkVM();
        }

        protected override ByIdLoggedWorkVM CreateBaseByIdVM()
        {
            return new ByIdLoggedWorkVM();
        }

        protected override BaseRepo<LoggedWork> CreateRepository()
        {
            return RepositoryFactory.GetLoggedWorksRepository();
        }

        protected override void PopulateViewModel(ByIdLoggedWorkVM model, LoggedWork entity)
        {
            int taskId = Convert.ToInt32(this.Request["taskID"]);

            if (entity.Id <= 0)
            {
                model.Id = entity.Id;
                model.TaskId = taskId;
                model.UserId = AuthenticationManager.LoggedUser.Id;
                model.TimeSpent = entity.TimeSpent;
                model.LoggedOn = DateTime.Now;
            }
            else
            {
                model.Id = entity.Id;
                model.TaskId = entity.TaskId;
                model.UserId = AuthenticationManager.LoggedUser.Id;
                model.TimeSpent = entity.TimeSpent;
                model.LoggedOn = DateTime.Now;
            }
        }

        protected override void PopulateEntity(LoggedWork entity, ByIdLoggedWorkVM model)
        {
            entity.Id = model.Id;
            entity.TaskId = model.TaskId;
            entity.UserId = model.UserId;
            entity.TimeSpent = model.TimeSpent;
            entity.LoggedOn = DateTime.Now;
        }

        protected override ActionResult Redirect(LoggedWork entity)
        {
            return RedirectToAction("Details", "TasksManager", new { id = entity.TaskId });
        }
    }
}

TaskManagerMVC/TaskManager/Views/Shared/_Partial/_CommentPartial.cshtml
@model TaskManager.VIewModels.TaskManager.TaskDetailsVm

<p>
    @Html.ActionLink("Create New", "Edit", "Comments", new { id = 0, taskid = Model.Id }, null)
</p>
<table class="table">
    <tr>
        <th>@Html.Label("Id")</th>
        <th>@Html.Label("ParentId")</th>
        <th>@Html.Label("Created BY")</th>
        <th>@Html.Label("Comments")</th>
        <th></th>
    </tr>
    @foreach (var item in Model.CommentsList)
            {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.TaskId
            </td>
            <td>
                @item.CreatedBy
            </td>
            <td>
                @item.Comments
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Comments", new { id = item.Id }, null) |
                @Html.ActionLink("Delete", "Delete", "Comments", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>

TaskManagerMVC/TaskManager/Views/Shared/_Partial/_LoggedWorkPartial.cshtml
@model TaskManager.VIewModels.TaskManager.TaskDetailsVm

<p>
    @Html.ActionLink("Create New", "Edit", "LoggedWork", new { id = 0, taskid = Model.Id }, null)
</p>
<table class="table">
    <tr>
        <th>@Html.Label("Id")</th>
        <th>@Html.Label("Task Id")</th>
        <th>@Html.Label("User Id")</th>
        <th>@Html.Label("TimeSpent")</th>
        <th>@Html.Label("Logged On")</th>
        <th></th>
    </tr>
    @foreach (var item in Model.LoggedWorkList)
            {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.TaskId
            </td>
            <td>
                @item.UserId
            </td>
            <td>
                @item.TimeSpent
            </td>
            <td>
                @item.LoggedOn
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "LoggedWork", new { id = item.Id, taskid = Model.Id }, null) |
                @Html.ActionLink("Delete", "Delete", "LoggedWork", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>