TaskManagerMVC/TaskManager/Controllers/TasksManagerController.cs
namespace TaskManager.Controllers
{
    using DataAccess.Entities;
    using DataAccess.Repositories;
    using Models;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Filter;
    using VIewModels.TaskManager;
    using VIewModels;
    using System.Linq;

    public class TasksManagerController : BaseController<Task, ByIdTaskVM, AllTasksVM, TasksFilter>
    {
        protected override AllTasksVM CreateBaseAllVM()
        {
            return new AllTasksVM();
        }

        protected override ByIdTaskVM CreateBaseByIdVM()
        {
            return new ByIdTaskVM();
        }

        protected override BaseRepo<Task> CreateRepository()
        {
            return RepositoryFactory.GetTasksRepository();
        }

        protected override void PopulateViewModel(ByIdTaskVM model, Task entity)
        {
            model.Id = entity.Id;
            model.Title = entity.Title;
            model.Description = entity.Description;
            UserRepo uRepo = RepositoryFactory.GetUsersRepository();
            List<User> users = uRepo.GetAll();
            model.ResponsibleUser = entity.ResponsibleUser;
            model.Status = entity.Status;
            if (entity.Id <= 0)
            {
                model.UserId = AuthenticationManager.LoggedUser.Id;
                model.CreateTime = DateTime.Now;
                model.Creator = AuthenticationManager.LoggedUser.Name;
            }
            else
            {
                model.Creator = entity.Creator;
                model.UserId = entity.UserId;
                model.CreateTime = entity.CreateTime;
            }
            model.LastChange = DateTime.Now;
        }
        
        protected override void PopulateEntity(Task entity, ByIdTaskVM model)
        {
            entity.Id = model.Id;
            entity.UserId = model.UserId;
            entity.Title = model.Title;
            entity.Description = model.Description;
            entity.ResponsibleUser = model.ResponsibleUser;
            entity.Creator = model.Creator;
            entity.Status = model.Status;
            entity.LastChange = DateTime.Now;
            entity.CreateTime = model.CreateTime;
        }

        protected override void DeleteFilter(int id)
        {
            CommentRepo comRepository = RepositoryFactory.GetCommentsRepository();
            List<Comment> comments = comRepository.GetAll().FindAll(com => com.TaskId == id);
            foreach (var com in comments)
            {
                comRepository.Delete(com);
            }
            LoggedWorkRepo loggedWorkRepo = RepositoryFactory.GetLoggedWorksRepository();
            List<LoggedWork> loggedWorks = loggedWorkRepo.GetAll().FindAll(lw => lw.TaskId == id);
            foreach (var lw in loggedWorks)
            {
                loggedWorkRepo.Delete(lw);
            }
        }
        
        [UserAuthentication]
        public ActionResult Details(int? id)
        {
            TaskDetailsVm model = new TaskDetailsVm();
            model.PagerComment = model.PagerComment ?? new Pager();
            model.PagerLogWork = model.PagerLogWork ?? new Pager();
            model.FilterComment = model.FilterComment ?? new CommentsFilter();
            model.FilterLoggedWorks = model.FilterLoggedWorks ?? new LoggedWorksFilter();
            TryUpdateModel(model);

            TaskRepo repository = RepositoryFactory.GetTasksRepository();
            Task task = repository.GetById(Convert.ToInt32(id));
            model.Id = task.Id;
            model.UserId = task.UserId;
            model.Title = task.Title;
            model.Description = task.Description;
            model.ResponsibleUser = task.ResponsibleUser;
            model.Creator = task.Creator;
            model.Status = task.Status;
            model.LastChange = task.LastChange;
            model.CreateTime = task.CreateTime;

            CommentRepo comRepo = RepositoryFactory.GetCommentsRepository();
            LoggedWorkRepo logWorkRepo = RepositoryFactory.GetLoggedWorksRepository();

            string action = this.ControllerContext.RouteData.Values["action"].ToString();
            string controller = this.ControllerContext.RouteData.Values["controller"].ToString();

            //comments
            model.FilterComment.Prefix = "FilterComment.";
            string commentsPrefix = "PagerComment.";
            model.FilterComment.TaskId = task.Id;
            int commentsResultCount = comRepo.Count(model.FilterComment.BuildFilter());
            model.PagerComment = new Pager(commentsResultCount, model.PagerComment.CurrentPage, model.PagerComment.PageSize, commentsPrefix, action, controller);
            model.FilterComment.ParentPager = model.PagerComment;
            model.CommentsList = comRepo.GetAll(model.FilterComment.BuildFilter(), model.PagerComment.CurrentPage, model.PagerComment.PageSize.Value).ToList();

            //loggedwork
            model.FilterLoggedWorks.Prefix = "FilterLoggedWorks.";
            string loggedWorkPrefix = "PagerLogWork.";
            model.FilterLoggedWorks.TaskId = task.Id;
            int loggedWorkResultCount = logWorkRepo.Count(model.FilterLoggedWorks.BuildFilter());
            model.PagerLogWork = new Pager(loggedWorkResultCount, model.PagerLogWork.CurrentPage, model.PagerLogWork.PageSize, loggedWorkPrefix, action, controller);
            model.FilterLoggedWorks.ParentPager = model.PagerLogWork;
            model.LoggedWorkList = logWorkRepo.GetAll(model.FilterLoggedWorks.BuildFilter(), model.PagerLogWork.CurrentPage, model.PagerLogWork.PageSize.Value).ToList();

            return View(model);
        }
    }
}

TaskManagerMVC/TaskManager/Controllers/UsersManagerController.cs
namespace TaskManager.Controllers
{
    using DataAccess.Repositories;
    using Models;
    using DataAccess.Entities;
    using VIewModels.UserManager;
    using System.Collections.Generic;
    using Filter;

    [AdminAuthentiation]
    public class UsersManagerController : BaseController<User, ByIdUserVM, AllUserVM, UsersFilter>
    { 
        protected override AllUserVM CreateBaseAllVM()
        {
            return new AllUserVM();
        }

        protected override ByIdUserVM CreateBaseByIdVM()
        {
            return new ByIdUserVM();
        }

        protected override BaseRepo<User> CreateRepository()
        {
            return RepositoryFactory.GetUsersRepository();
        }
        
        protected override void PopulateViewModel(ByIdUserVM model, User entity)
        {
            model.Id = entity.Id;
            model.Username = entity.Username;
            model.Password = entity.Password;
            model.Name = entity.Name;
            model.Email = entity.Email;
            model.IsAdmin = entity.IsAdmin;
        }

        protected override void PopulateEntity(User entity, ByIdUserVM model)
        {
            entity.Id = model.Id;
            entity.Username = model.Username;
            entity.Password = model.Password;
            entity.Name = model.Name;
            entity.Email = model.Email;
            entity.IsAdmin = model.IsAdmin;
        }

        protected override void DeleteFilter(int id)
        {
            TaskRepo taskRepository = RepositoryFactory.GetTasksRepository();
            List<Task> tasks = taskRepository.GetAll().FindAll(task => task.UserId == id && task.ResponsibleUser == id);
            foreach (var task in tasks)
            {
                taskRepository.Delete(task);
            }

            List<Task> tasksRespU = taskRepository.GetAll();
            foreach (var task in tasksRespU)
            {
                if (task.ResponsibleUser == AuthenticationManager.LoggedUser.Id)
                {
                    task.UserId = AuthenticationManager.LoggedUser.Id;

                    taskRepository.Save(task);
                }
            }

            CommentRepo comRepository = RepositoryFactory.GetCommentsRepository();
            List<Comment> comments = comRepository.GetAll().FindAll(com => com.CreatedBy == id);
            foreach (var com in comments)
            {
                comRepository.Delete(com);
            }

            LoggedWorkRepo loggedWorkRepo = RepositoryFactory.GetLoggedWorksRepository();
            List<LoggedWork> loggedWorks = loggedWorkRepo.GetAll().FindAll(lw => lw.UserId == id);
            foreach (var lw in loggedWorks)
            {
                loggedWorkRepo.Delete(lw);
            }
        }
    }
}

TaskManagerMVC/TaskManager/Views/Shared/_FilterPartial.cshtml
@model System.Object

@{
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();
    string action = this.ViewContext.RouteData.Values["action"].ToString();
    string namePrefix = Model.GetType().GetProperty("Prefix").GetValue(Model, null).ToString();
    string idPrefix = namePrefix.Replace(".", "_");
    var parentPager = (TaskManager.VIewModels.Pager)Model.GetType().GetProperty("ParentPager").GetValue(Model, null);
    var editableProperties = new Dictionary<System.Reflection.PropertyInfo, string>();
    foreach (System.Reflection.PropertyInfo pi in Model.GetType().GetProperties())
    {
        object obj = pi.GetCustomAttributes(false).FirstOrDefault(a => a is TaskManager.Tools.FilterPropertyAttribute);
        if (obj != null)
        {
            TaskManager.Tools.FilterPropertyAttribute attrib = (TaskManager.Tools.FilterPropertyAttribute)obj;
            editableProperties.Add(pi, attrib.DisplayName);
        }
    }

    var props = Model.GetType().GetProperties();
    string id = "";
    foreach (var prop in props)
    {
        if (prop.Name == "TaskId")
        {
            id = prop.GetValue(Model).ToString();
        }
    }
}

<form action="/@controller/@action/@id" method="get">
    @foreach (string key in this.Request.QueryString.Keys)
    {
        if (!key.StartsWith(namePrefix) && key != parentPager.Prefix + "CurrentPage")
        {
            @Html.Hidden(key, this.Request.QueryString[key]);
        }
    }

    @foreach (var kvp in this.ViewContext.RouteData.Values)
    {
        if (kvp.Key != "controller" && kvp.Key != "action" && kvp.Key != parentPager.Prefix + "CurrentPage" && !kvp.Key.StartsWith(namePrefix))
        {
            @Html.Hidden(kvp.Key, kvp.Value);
        }
    }

    <p>
        @foreach (var kvp in editableProperties)
        {
            @Html.Label(idPrefix + kvp.Key.Name, kvp.Value)
            @Html.TextBox(namePrefix + kvp.Key.Name, kvp.Key.GetValue(Model, null))
        }
        <input type="submit" value="Search" />
    </p>
</form>

TaskManagerMVC/TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="width: 75%;">
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @if (TaskManager.Models.AuthenticationManager.LoggedUser == null)
                {
                    @Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "navbar-brand" });
                }
                @if (TaskManager.Models.AuthenticationManager.LoggedUser == null)
                {
                    @Html.ActionLink("Register", "Register", "Home", new { area = "" }, new { @class = "navbar-brand" });
                }
                <div style="float:right;">
                    @if (TaskManager.Models.AuthenticationManager.LoggedUser != null)
                    {
                        @Html.ActionLink("Tasks Manager", "Index", "TasksManager", new { area = "" }, new { @class = "navbar-brand" })
                        if (TaskManager.Models.AuthenticationManager.LoggedUser.IsAdmin == true)
                        {
                            @Html.ActionLink("Users Manager", "Index", "UsersManager", new { area = "" }, new { @class = "navbar-brand" })
                        }
                    }
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VladislavKVZ</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

TaskManagerMVC/TaskManager/Views/Shared/_PagingPartial.cshtml
@model TaskManager.VIewModels.Pager

@{
    string currentPageTemplate = Url.Action(Model.Action, Model.Controller) + "?";
    string pageSizeTemplate = Url.Action(Model.Action, Model.Controller) + "?";
    foreach (var i in this.Request.QueryString.Keys)
    {
        if (i.ToString() != Model.Prefix + "CurrentPage")
        {
            currentPageTemplate += i.ToString() + "=" + Request[@i.ToString()] + "&";
        }

        if (i.ToString() != Model.Prefix + "PageSize" && i.ToString() != Model.Prefix + "CurrentPage")
        {
            pageSizeTemplate += i.ToString() + "=" + Request[@i.ToString()] + "&";
        }
    }
    foreach (var i in this.Request.Form.Keys)
    {
        currentPageTemplate += i.ToString() + "=" + Request[@i.ToString()] + "&";
        pageSizeTemplate += i.ToString() + "=" + Request[@i.ToString()] + "&";
    }
}
<!-- there is a potential bug here. If a param comes from the route data it's not a named parameter and can't be accessed through the Request! -->
@if (Model.EndPage > 0)
{
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@currentPageTemplate@(Model.Prefix + "CurrentPage=" + 1)">First</a>
            </li>
            <li>
                <a href="@currentPageTemplate@(Model.Prefix + "CurrentPage=" + (Model.CurrentPage-1) )">Previous</a>
            </li>
        }

        @for (var page = Model.StartPage; page <= Model.EndPage; page++)
        {
            <li class="@(page == Model.CurrentPage ? "active" : "")">
                <a href="@currentPageTemplate@(Model.Prefix + "CurrentPage=" + page)">@page.ToString()</a>
            </li>
        }

        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li>
                <a href="@currentPageTemplate@(Model.Prefix + "CurrentPage=" + (Model.CurrentPage+1) )">Next</a>
            </li>
            <li>
                <a href="@currentPageTemplate@(Model.Prefix + "CurrentPage=" + Model.TotalPages  )">Last</a>
            </li>
        }
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Model.PageSize<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="@pageSizeTemplate@(Model.Prefix + "CurrentPage=1")&@(Model.Prefix + "PageSize=" + 1)">1</a>
                </li>
                <li>
                    <a href="@pageSizeTemplate@(Model.Prefix + "CurrentPage=1")&@(Model.Prefix + "PageSize=" + 5)">5</a>
                </li>
                <li>
                    <a href="@pageSizeTemplate@(Model.Prefix + "CurrentPage=1")&@(Model.Prefix + "PageSize=" + 10)">10</a>
                </li>
                <li>
                    <a href="@pageSizeTemplate@(Model.Prefix + "CurrentPage=1")&@(Model.Prefix + "PageSize=" + 15)">15</a>
                </li>
                <li>
                    <a href="@pageSizeTemplate@(Model.Prefix + "CurrentPage=1")&@(Model.Prefix + "PageSize=" + 20)">20</a>
                </li>
            </ul>
        </li>
    </ul>
}            